### ISSUE TITLE
Assignment 2: Issue with running docker container nodejs

### ISSUE THREAD

**Issue by shubhamkr1** [airavata-courses/shubhamkr1#11]
I have created Dockerfile with below content -
FROM node:8.5-alpine
ADD . /node
WORKDIR /node
ADD package.json /node/
RUN npm install 
EXPOSE 4444 4445
ENTRYPOINT ["node","index.js"]

I am able to build image from this but during runtime I get error attached in image
![erroe_dock1](https://user-images.githubusercontent.com/22971721/30410732-f13372c0-98da-11e7-8667-e469b355c994.png)

**Comment by tilaks26** [comment]
Please check if you've installed your dependencies. It's clear that you've not installed something that you're supposed to. The path shows something related to sqlite3.

[Link 1](https://stackoverflow.com/questions/42040317/cannot-find-module-for-a-node-js-app-running-in-a-docker-compose-environment)
[Link 2](https://stackoverflow.com/questions/30043872/docker-compose-node-modules-not-present-in-a-volume-after-npm-install-succeeds)

P.S. - From next time when you open an issue, you're supposed to tag the AIs, not assign them to the issues. Ultimately, you're the one who is supposed to resolve issues. Not the AIs. So, you will be the assignee for your issues.

Thanks.
