### ISSUE TITLE
Add missing steps to README

### ISSUE THREAD

**Issue by neeraj-lad** [airavata-courses/shubhamkr1#3]
Additional packages required:
via node:
1. sqlite3
2. request

via pip:
1. requests

Need to do
`mvn clean install` to generate the `target` directory.

**Comment by shubhamkr1** [comment]
I have added jar file, so there is no need to run mvn clean install. Also, I did "npm install <package> --save" so the dependencies are present in node service folders. I will add for python dependency.

**Comment by shubhamkr1** [comment]
Added steps in Wiki.
