### ISSUE TITLE
Readme.md update

### ISSUE THREAD

**Issue by jeffreypeter** [airavata-courses/shubhamkr1#5]
NodeJs
(Optional) To Install node libraries
> npm install 
Java
(Optional) To generate the jar file initially
> mvn clean install

**Comment by shubhamkr1** [comment]
Moved everything on Wiki. Changed readme.

**Comment by jeffreypeter** [comment]
@shubhamkr1 
(Optional) To generate the jar file initially
`mvn clean install`
Add this to your wiki as your target folder is not created and so we won't able to run the java server.
