### ISSUE TITLE
Assignment 1: Comments

### ISSUE THREAD

**Issue by Ameya05** [airavata-courses/shubhamkr1#9]
All microservices are running fine.

There is an UI and a API Gateway, 
but the UI index.html has **redirect links** to the microservices.

```
<ul>
            <li>
              <a href="http://localhost:3000/service1/">Node Microservice</a>
            </li>
 </ul>
```

Instead, the expected workflow is 

1. UI invokes the API Gateway endpoint either synchronously or async using AJAX.
2. The API Gateway initiates requests to the microservices. 
3. Based on the responses from the microservices, the API Gateway displays data back to the UI.

The User should not be redirected away from the UI. The API Server is not serving the purpose at the moment. 

Please implement an API server which acts as a gateway to the microservices. You could refer the [lecture slides](http://courses.airavata.org/slides/SICE-Fall17-B649-Assignment-1.pdf) for a better understanding.

**Comment by shubhamkr1** [comment]
I have made the mentioned changes. I have changed UI and Gateway. Please check.

**Comment by Ameya05** [comment]
Looks like your instructions are not updated.
1. Please update the instructions in your Wiki about which index.html file is supposed to be used.
The wiki states that it is in api_server/static , but the changes you made in your last commit are in the index.html file which is in the root directory.

2. Tie your commits to the issue by adding a message "#commit_number" in the commit. e.g. to reference the next commit with this issue, you could use a commit message like "#9 : Fixed index.html file "

3. I tried the index.html in the root directory, but it is throwing an error. I Noticed that you changed the node.js microservcie endpoint, update ur gateway/ instructions accordingly

4. The UI has to be served through a server, and should not be static file access. Add instructions on how to access the UI from browser. for e.g. **Open https://localhost:20000/apigateway/index.html**

**Comment by shubhamkr1** [comment]
Made the specified changes, please check.

**Comment by Ameya05** [comment]
I would be regrading your assignment, let me know which commit / branch to check.

**Comment by shubhamkr1** [comment]
Please check master branch. Latest Commit -- 9241706c074586ed3531464baf2d128fc0076ada.

**Comment by Ameya05** [comment]
Working as expected, closing this issue.
